// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcxrcfpuyjlgbbruaklg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeHJjZnB1eWpsZ2JicnVha2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MjE1NjQsImV4cCI6MjA1MTM5NzU2NH0.Kdc8Rv7001fC4TlanfCXE7bCvtgPOLGXYsYMs2ZSuvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);